CREATE DATABASE IF NOT EXISTS TASK;
USE TASK;

CREATE TABLE IF NOT EXISTS TASK (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(100) NOT NULL,
  RESPONSIBLE VARCHAR(100) NOT NULL
);